### ISSUE TITLE
runtime 'org.apache.camel:camel-mail:2.12.1' isn't working

### ISSUE THREAD

**Issue by tothertomb** [padcom/grails-routing#40]
Following error when trying to install camel mail. I'm on grails 2.3.5.

Resolve error obtaining dependencies: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy:513)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy)
    at grails.util.BuildSettings$_getDefaultTestDependencies_closure14.doCall(BuildSettings.groovy:587)
    at grails.util.BuildSettings$_getDefaultTestDependencies_closure14.doCall(BuildSettings.groovy)
    at grails.util.BuildSettings.getDefaultTestDependencies(BuildSettings.groovy:581)
    at grails.util.BuildSettings.getTestDependencies(BuildSettings.groovy:562)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:460)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    ... 6 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:342)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:649)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:247)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:437)
    ... 8 more
| Error Resolve error obtaining dependencies: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
| Error Resolve error obtaining dependencies: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy:513)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy)
    at grails.util.BuildSettings$_getDefaultRuntimeDependencies_closure15.doCall(BuildSettings.groovy:625)
    at grails.util.BuildSettings$_getDefaultRuntimeDependencies_closure15.doCall(BuildSettings.groovy)
    at grails.util.BuildSettings.getDefaultRuntimeDependencies(BuildSettings.groovy:619)
    at grails.util.BuildSettings.getRuntimeDependencies(BuildSettings.groovy:601)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:460)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    ... 6 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:342)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:649)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:247)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:437)
    ... 8 more
| Error Resolve error obtaining dependencies: Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
| Error Could not find artifact org.apache.camel:camel-mail:zip:2.12.1 in grailsCentral (http://repo.grails.org/grails/plugins)
| Run 'grails dependency-report' for further information.

**Comment by takeitallsource** [comment]
Hi @tothertomb please make sure that you put your definition on the dependencies section instead of the plugin section.

Regards.
